### ISSUE TITLE
HttpClientFactory, xUnit2 and parallelism - weird success/failed tests

### ISSUE THREAD

**Issue by robertmuehsig** [PureKrome/HttpClient.Helpers#1]
Hi, I'm using your latest and greatest library, but after I updated to xUnit2 I'm seeing some weird behaviour. Tests that are touching the HttpClientFactory are failing or succeeding randomly, but I'm not sure if it is a "problem" in your helper library or a test design problem.

For example (without any code chances)

![image](https://cloud.githubusercontent.com/assets/756703/6953347/02c9a6e6-d8c9-11e4-803f-1793217be8e1.png)

![image](https://cloud.githubusercontent.com/assets/756703/6953362/20a70924-d8c9-11e4-9a21-03cb7671bf15.png)

![image](https://cloud.githubusercontent.com/assets/756703/6953376/37b9c43a-d8c9-11e4-9064-08d5ee179e84.png)

Even the console test runner shows mixed results. After some headaches I found the reason: With xUnit2 tests can now run in parallel:
http://xunit.github.io/docs/running-tests-in-parallel.html

Now pure guessing from me; Because HttpClientFactory is a static thing and it is used in parallel from different tests the tests behave very differently.

Is there a way to inject the HttpClientFactory inside the test class, so each test have their own factory?

My code can be found here:
https://github.com/Code-Inside/Sloader

**Comment by robertmuehsig** [comment]
To get things running I decided to turn of the parallel support for now https://github.com/Code-Inside/Sloader/commit/c7140f90440324689031728ed1bdac27354e1b98

But I don't think this is a good solution for the long run - or did I do something stupid in my test code? Maybe you have a good idea :)

**Comment by PureKrome** [comment]
First question - are you using the latest version of `HttpClientFactory` ? I've had issues with a previous release about how the Factory wasn't really thread safe.

**Comment by robertmuehsig** [comment]
I think yes. I'm using this packages:

```
<package id="Microsoft.Net.Http" version="2.2.29" targetFramework="net45" />
<package id="WorldDomination.HttpClient.Helpers" version="2.3.0" targetFramework="net45" />
```

**Comment by PureKrome** [comment]
OK, latest is 2.3.0. can u try that please?

**Comment by robertmuehsig** [comment]
If you mean the WorldDomination.Net.Http package: It is already on 2.3.0 and it fails with the new xunit parallelism. Maybe it would work if I moved each test to its own test class, but this seems not a very elegant solution. 

Or is something wrong in my tests, e.g. https://github.com/Code-Inside/Sloader/blob/master/tests/Sloader.Crawler.Tests/FeedCrawlerTests/FacebookShareCounterTests.cs ?

**Comment by PureKrome** [comment]
> If you mean the WorldDomination.Net.Http package: It is already on 2.3.0

huh? it's on `2.2.29` ?

Oh dang!! that's the `M.Net.Http` package! Ha - my bad :blush: soz ...

> Maybe it would work if I moved each test to its own test class, but this seems not a very elegant solution.

Nope. that's just avoiding the _real_ problem, which is a (IMO) thread safe issue. The library _should_ be able to work properly in parallel. This suggests the code is crap :/ So I need to figure out _what_ is going on.

**Comment by robertmuehsig** [comment]
Yupp, no problem :-) 

How could I help - threading issues are always... mh... interesting / challenging?  ;)

**Comment by PureKrome** [comment]
Very good question :/ I really don't know TBH. I'm having a look at the code right now (first, updating `xunit` to `xunit-core`) and then seeing how i'm handling `static's` etc :(

**Comment by PureKrome** [comment]
The problem is basically, the factory can only _really_ take one -pre-set- fake'd item .. and then everyone thread is trying to grab that item.

So the first thread says: Factory, when i ask for an HttpClient, i want a `red` one.. (whatever that is). Ok, great. Then .... a nanosecond later, a _different_ piece of code says: Factory! here's a `blue` one .. gimme that when I ask for it...

fast forward 2 secs later and the first code says: can i have my `red` thing which I gave u earlier .. and the Factory goes 'meh' and returns the _last_ thing it was given .. which is a `blue` thing in this case.

So i'll need to force the user to use some TAGGING mechanism when setting/getting the `HttpClient`, otherwise it's unknown.

for example.

```
HttpClientFactory.MessageHandler["red"] = whatever;
...
using (var httpClient = HttpClientFactory.GetHttpClient["red"])
{ ... }
```

does that make sense?

**Comment by robertmuehsig** [comment]
Mh... in my case I just want to mock different "results" in the test case. Such tagging as you described would do a mess in the production code. 

Currently HttpClientFactory is static, but what if I could just inject the factory in my component: 

e.g:

```
    public class FacebookShareCountLoader(HttpClientFactory factory)
    {
        _factory = factory;
    }

    public async Task<int> GetAsync(string url)
    {
        ...
        using (var httpClient = _factory.GetHttpClient())
```

This would be a pretty common approach, but maybe there are some drawbacks with this.

**Comment by PureKrome** [comment]
Don't inject the factory, inject the `MessageHandler`.

eg.

```
private readonly HttpMessageHandler _messageHandler;
public FSCL(HttpMessageHandler messageHandler == null)
{
    _messageHandler = HttpMessageHandler;
}

public async Task<int> GetAsync(string url)
{
    ...
    using (var httpClient = HttpClientFactory.GetHttpClient(_messageHandler))
    { ... }
}
```

try that!

> Currently HttpClientFactory is static, but what if I could just inject the factory in my component

Injecting a static is .. well .. useless :) it's still a static.. which is the problem, here.

**Comment by robertmuehsig** [comment]
Ah, pretty good idea... I will try this later when I'm home. 

I was thinking about which part should be injected, but the important part is the fakemessagehandler, so it makes sense to inject that and leave the HttpClientFactory as is.

**Comment by PureKrome** [comment]
Kewl - and the optional `HttpMessageHandler` instance in `GetHttpClient(..)` was added in `v 2.3.0` because of a `dispose` bug.

I'm thinking now that I need to refactor that property (which won't effect you).

oh look! i've already started this change, 20 mins ago :)

**Comment by PureKrome** [comment]
Hi @robertmuehsig :wave:

So, I did some code last night. Slept on some final changes I wasn't soooo sure about. Finished up and pushed code up. Because I've changed the method signatures (ie. the API has changed)... i've up'd the version to `3.0.1` ... as with the _schemantic versioning_ rules.

New [NuGet package here](https://www.nuget.org/packages/WorldDomination.HttpClient.Helpers/).
Wiki documentation updated to reflect new changed.

NOTE: 
- `GetHttpClient()` is now removed.
- `GetHttpClient(..)` now takes a fake message handler (if provided via ctor injection DI/IoC) or via the a string key.

**Comment by robertmuehsig** [comment]
So, I used the new `GetHttpClient(..)` with the injected `FakeMessageHandler` in the tests and use the default `HttpClientMessageHandler` in the production code and so far everything seems fine.

Also no weird errors for the parallel tests. I think it's solved. Thanks for the fast code changes!

**Comment by PureKrome** [comment]
Great!! At first I felt a bit _urgh_ over the extra bit of complication, but it seems worth it.

Fixed in 734dd787d652c6924f51128de7c790af254e07b4

**Comment by robertmuehsig** [comment]
I had a small "problem" regarding your default disposing-pattern and want to share my experience with you. 
With the new version I inject the FakeHttpHandler in my tests and use a pretty simple approach in the production code: https://github.com/Code-Inside/Sloader/blob/master/src/Sloader.Crawler/Feed/TwitterTweetCountLoader.cs 

The problem was that the GetAsync-method was used inside a loop and only the first one was able to retrieve data, all following failed because of the dispose = true in the HttpClientFactory.

I stumpled on this SO Question: http://stackoverflow.com/questions/15705092/do-httpclient-and-httpclienthandler-have-to-be-disposed and it seems that disposing is not necessary. 

Now I just use the overloaded GetHttpClient and don't dispose the HttpClientHandler and it seems to work. I'm not sure if this is a clever approach, but it worked for me.

**Comment by PureKrome** [comment]
Nope - _you need to dispose_. 

The trick is to setup your `FakeHttpMessageHandler` to -not- _internally_ dispose of whatever internal client is hidden away.

The scenario for this is to re-use some internal component when a number of calls are being made with the same instance. 

So - [this here's an integration test-example of what I'm done - doing 2x calls using the same instance](https://github.com/PureKrome/HttpClient.Helpers/blob/master/Code/HttpClient.Helpers.Tests/IntegrationFacts.cs#L50) ...
1. Create the fake message handler (nothing new here)

```
var messageHandler = new HttpClientHandler
    {
        Credentials = new NetworkCredential("api", "hi there!")
    };
```
1. Tell the `Factory` to **NOT** dispose of the `client` after it's executed.
   *\* THIS IS THE TRICK -> Notice the last parameter). By default, it's `true` **

```
var key = Guid.NewGuid().ToString();
HttpClientFactory.AddMessageHandler(messageHandler, key, false);
```
1. Now do 2+ calls to some endpoint, using the same instance...

```
using (var httpClient = HttpClientFactory.GetHttpClient(key))
{
    html1 = await httpClient.GetStringAsync("http://www.google.com.au");
}

using (var httpClient = HttpClientFactory.GetHttpClient(key))
{
    html2 = await httpClient.GetStringAsync("http://www.google.com.au");
}

```

and it should work.

This example is actually hitting the end point. You can swap the messageHandler for a fake one -> `FakeHttpMessageHandler`.

Lastly, you can use _constructor injection_ also - it has a param option (which is `true` by default, and you need to toggle that to `false`).

I'll need to create an issue to create some wiki page about this problem.

**Comment by robertmuehsig** [comment]
Ay, I just will implement dispose on my components as well and will dispose the underlying httpmessagehandler there. That seems clean to me - thanks!
