### ISSUE TITLE
Need a way to verify operation was called

### ISSUE THREAD

**Issue by RPM1984** [PureKrome/HttpClient.Helpers#11]
If we are doing something like a HTTP DELETE where there is no returned body/headers (usually just a status code), then we need a way in our tests to verify the operation was called (since the calling method will return `void`).

Suggestion: add `WasCalled` property (only `get` property) to `HttpMessageOptions`, which can then be checked in the test.

e.g

```
// Arrange.
// ... snip ...
var options = new HttpMessageOptions
{
    HttpMethod = HttpMethod.Delete,
    RequestUri = "http://api.com/user",
    HttpResponseMessage = new HttpResponseMessage(HttpStatusCode.NoContent)
};
var fakeMessageHandler = new FakeHttpMessageHandler(options);

// Act.
var client = new TestClientClient(baseUrl, fakeMessageHandler);

// Act.
await client .DeleteUserAsync(someoperation);

// Assert.
options.WasCalled.ShouldBeTrue();
```

**Comment by PureKrome** [comment]
Fixed in #12
