### ISSUE TITLE
Request not attached to Response

### ISSUE THREAD

**Issue by Kralizek** [PureKrome/HttpClient.Helpers#20]
The current request is not attached to the response returned by FakeHttpHandler

**Comment by PureKrome** [comment]
Hi @Kralizek - I don't really understand the reason behind this issue and PR 😊 

I can see that you make a new copy of the `HttpResponseMessage` result but I don't understand why?

Can you explain what was wrong before and what this now solves? What is an example scenario, also?

**Comment by Kralizek** [comment]
Hi @PureKrome 

You can look at this method https://github.com/Kralizek/Assembla.Connector/blob/master/src/Kralizek.Assembla.Connector/Connector/HttpAssemblaClient.cs#L232

It tries to log the result of a request including fields both from the response and the request itself.

In the PR I submitted, when copying the HttpResponseMessage, I also attach the request [here](https://github.com/Kralizek/HttpClient.Helpers/commit/a7a243f5a4f57c9f54ceae641d7c95b6bd2ef276#diff-2771ece00f76910be27dedeb4fd80432R96)

**Comment by PureKrome** [comment]
Hi @Kralizek - Why are you _cloning_ the `HttpResponseMessage` ? I see how the it can accept an `HttpRequestMessage` .. so I get that now (and why that was important to you).

But why the clone/copy? Why not just set the request, on the way out?

e.g.
```
// Increment the number of times this option had been 'called'.
            IncrementCalls(expectedOption);

            // HERE HERE HERE - Pass the request along.
            expectedOption.HttpResponseMessage.RequestMessage = request;

            tcs.SetResult(expectedOption.HttpResponseMessage);
            return tcs.Task;
```

**Comment by Kralizek** [comment]
The risk was that the HttpRequestMessage attached to the response was tempered in some way (e.g. Disposed) by the code of the system under test.

**Comment by PureKrome** [comment]
Hmm. I think I'm actually OK with that, though.

I'm thinking: this is the _real_ `request` instance that was used. Sure, it could be disposed by some outside code (ie. test code) ... but the instance still exists. AND more importantly, if someone tries to do something with that instance ... and it's a COPY ... and now it does something when it shouldn't .. that would be bad IMO.

**Comment by PureKrome** [comment]
Hi @Kralizek  - I've now got a beta/development version of this library hosted up in my nuget development hosting server:

https://www.myget.org/feed/Packages/pk-development
So you can download the nuget package there or just add that custom nuget feed and test it out there.

It's .NETStandard 1.4 which means the minimum is .NET 4.6.1.

Can you please give that a run and see if it's working for you, etc? plz?

**Comment by PureKrome** [comment]
Happy to re-open this if my current understanding/decision is unacceptable/poor/crap, etc.
