### ISSUE TITLE
Package fails with .NET Core 1.1

### ISSUE THREAD

**Issue by bdparrish** [PureKrome/HttpClient.Helpers#22]
Restoring packages for 
Package WorldDomination.HttpClient.Helpers 5.1.0 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package WorldDomination.HttpClient.Helpers 5.1.0 supports: net45 (.NETFramework,Version=v4.5)
Package Microsoft.Net.Http 2.2.29 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.Net.Http 2.2.29 supports:
  - monoandroid (MonoAndroid,Version=v0.0)
  - monotouch (MonoTouch,Version=v0.0)
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
  - portable-net40+sl4+win8+wp71+wpa81 (.NETPortable,Version=v0.0,Profile=net40+sl4+win8+wp71+wpa81)
  - portable-net45+win8 (.NETPortable,Version=v0.0,Profile=Profile7)
  - portable-net45+win8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile111)
  - sl4-wp71 (Silverlight,Version=v4.0,Profile=WindowsPhone71)
  - win8 (Windows,Version=v8.0)
  - wpa81 (WindowsPhoneApp,Version=v8.1)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
Package Microsoft.Bcl 1.1.10 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.Bcl 1.1.10 supports:
  - monoandroid (MonoAndroid,Version=v0.0)
  - monotouch (MonoTouch,Version=v0.0)
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
  - portable-net40+sl4+win8 (.NETPortable,Version=v0.0,Profile=net40+sl4+win8)
  - portable-net40+sl4+win8+wp71+wpa81 (.NETPortable,Version=v0.0,Profile=net40+sl4+win8+wp71+wpa81)
  - portable-net40+sl4+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=net40+sl4+win8+wp8+wpa81)
  - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
  - portable-net40+win8 (.NETPortable,Version=v0.0,Profile=Profile5)
  - portable-net40+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=net40+win8+wp8+wpa81)
  - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
  - portable-net45+win8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile111)
  - portable-net451+win81 (.NETPortable,Version=v0.0,Profile=Profile44)
  - portable-net451+win81+wpa81 (.NETPortable,Version=v0.0,Profile=Profile151)
  - portable-win81+wp81+wpa81 (.NETPortable,Version=v0.0,Profile=Profile157)
  - sl4 (Silverlight,Version=v4.0)
  - sl4-wp71 (Silverlight,Version=v4.0,Profile=WindowsPhone71)
  - sl5 (Silverlight,Version=v5.0)
  - win8 (Windows,Version=v8.0)
  - wp8 (WindowsPhone,Version=v8.0)
  - wpa81 (WindowsPhoneApp,Version=v8.1)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
One or more packages are incompatible with .NETCoreApp,Version=v1.1.
Package restore failed. Rolling back package changes for 'API.Tests'.
Time Elapsed: 00:00:00.8956040
========== Finished ==========

**Comment by PureKrome** [comment]
Question: Do you need this library to target a particular .NET Standard?

**Comment by PureKrome** [comment]
OK - looks like `Microsoft.Net.Http` is for the older 4.5 framework, which I want to move off .. and is replaced by `System.Net.Http` nuget package instead.

**Comment by PureKrome** [comment]
Hi @bdparrish  - I've now got a beta/development version of this library hosted up in my nuget development hosting server:

> `https://www.myget.org/feed/Packages/pk-development`

So you can download the nuget package there or just add that custom nuget feed and test it out there.

It's `.NETStandard 1.4` which means the minimum is `.NET 4.6.1`.

**Comment by ghost** [comment]
when Im adding this to my nuget feed then I see this error : 

    [Http-helpers] 'doctype' is an unexpected token. The expected token is 'DOCTYPE'. Line 1, position 3.

**Comment by PureKrome** [comment]
How are u adding this to your nuget feed?

Here's an example of my `nuget.config` file I have sitting in the root directory of my repository which wants to access this `dev` nuget-feed :

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear/>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="myget-pk-dev" value="https://www.myget.org/F/pk-development/api/v2" />
    <add key="Localhost" value="C:\Projects\Temp NuGet Packages" />
  </packageSources>
</configuration>
```

I'm also assuming you could replace the `value` from the `v2` url to the `v3` url too..

```
<add key="myget-pk-dev" value="https://www.myget.org/F/pk-development/api/v3/index.json" />
```

**Comment by ghost** [comment]
For me this package is running fine on dotnet core 1.1
