### ISSUE TITLE
Dnx support?

### ISSUE THREAD

**Issue by dotnetshadow** [PureKrome/HttpClient.Helpers#3]
Hi I was wondering if this would work in a dnx project? ASP.NET 5 vnext?

**Comment by PureKrome** [comment]
I have absolutely no idea :blush: I'm waiting for RC2 to hit before I look into anything vNexty.

**Comment by PureKrome** [comment]
Just an update here. 

So far, there's no `IHttpClient` in .NET Core, so i'll look at migrating this to .NET Core ... but not yet. Waiting for the .json project format to be replaced with csproj format, before I jump into .NET Core.

**Comment by Kralizek** [comment]
I just added this PR #18

**Comment by PureKrome** [comment]
Also - this fix for this issue will be .NET **Standard** support, as DNX has gone.

**Comment by PureKrome** [comment]
@dotnetshadow  & @Kralizek - I've now got a beta/development version of this library hosted up in my nuget development hosting server:

> `https://www.myget.org/feed/Packages/pk-development`

So you can download the nuget package there or just add that custom nuget feed and test it out there.

It's `.NETStandard 1.4` which means the minimum is `.NET 4.6.1`.

**Comment by PureKrome** [comment]
Hi again folks - just curious if you've had a chance to test out the dev build I've put up recently?

If you don't know how to add a dev build to nuget, a quick trick is to add a `nuget.config` file to the root directory of your repository and add something like this, to the file...

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear/>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="myget-pk-dev" value="https://www.myget.org/F/pk-development/api/v2" />
    <add key="Localhost" value="C:\Projects\Temp NuGet Packages" />
  </packageSources>
</configuration>
```
