### ISSUE TITLE
Do you really need all Core (System.*) packages on Full .NET?

### ISSUE THREAD

**Issue by abatishchev** [PureKrome/HttpClient.Helpers#30]
Is it possible to adjust the nuspec so when a full .NET project references the package then no Core packages would be installed?

**Comment by PureKrome** [comment]
I have no idea 😊 

I _personally_ only want the _least_ amount of dependencies required to be pulled down by consumers/developers (such as yourself).

As such I actually don't have any idea how to do this 😊 

Any clues would really help me. I might see if I can pull in some outside help on this too.

So yes - I'd totally love this to be a light, minimal nuget package/library.

![](https://media.giphy.com/media/SRx5tBBrTQOBi/giphy.gif)

**Comment by abatishchev** [comment]
>I personally only want the least amount of dependencies required to be pulled down
Exactly.

I'll take a look.

**Comment by abatishchev** [comment]
Check this out, how people manage to have different set of dependencies (dependency group in official jargon) for different target frameworks:

- https://github.com/nunit/nunit/blob/master/nuget/framework/nunit.nuspec
- https://github.com/xunit/xunit/blob/master/src/xunit.extensibility.core.nuspec

Or any other popular package's nuspec

**Comment by PureKrome** [comment]
i'm not using `nuspec` anymore :(

**Comment by abatishchev** [comment]
I see, you have C#/.NET Core  project with does everything for you, kind of? I find it lacking major features such as dependencies management (min/max version, target framework). Think to switch to nuspec in Jwt so what suggest to you too.

**Comment by PureKrome** [comment]
Before I switch, etc. I guess I need to understand how having different frameworks will then have different dependencies, etc.

I'm still stuck on that step 😊

**Comment by abatishchev** [comment]
Maybe this idea for a switch is too far fetched :)

[Here's](https://www.bartwolff.com/Blog/2017/03/20/targeting-multiple-net-platforms-in-a-single-nuget-package-w) what I think you need: conditional references. I'd target framework is net462 then reference only bcl dlls and regular nugets, if netstandard then core nugets.

**Comment by abatishchev** [comment]
Hey, I learned how to specify other than the exact version of depended nuget package in csproj directly, see [AzSdk.reference.props](https://github.com/Azure/azure-sdk-for-net/blob/6eff4c4113fcda3ab53a1ccf39b2f55fbb1efea1/src/SDKs/AzSdk.reference.props).

**Comment by abatishchev** [comment]
Please adjust your csproj to reference Core packages only if target platform=nestandard

**Comment by PureKrome** [comment]
OK - i'll implement this as .NET Standard 2.0 which reduces the dep size.

**Comment by PureKrome** [comment]
Fixed in #34 

@abatishchev 👋 I know this is an old issue, but I finally got around to updating this library to .NET Standard 2.0. Code is up and a new release is up on NuGet.

Hope this isn't too late and helps. If not, keep adding to the discussion here and I'll re-open and learn about my mistakes and fix up.
