### ISSUE TITLE
Error occurs when URL contains URL encoded values.

### ISSUE THREAD

**Issue by RPM1984** [PureKrome/HttpClient.Helpers#6]
Try a URL like this:

```
http://www.whatever.com/something?json=%7B%0A%20%20%20%22Ids%22%3A%20%5B16036%2C1%5D%0A%7D
```

The `CreateDictionaryKey` method is erroring, presumably because of the `string.Format` not liking the braces...

**Comment by PureKrome** [comment]
Fixed in #7.

**Comment by RPM1984** [comment]
👍 ETA on new NuGet release?

**Comment by PureKrome** [comment]
It's there now : https://www.nuget.org/packages/WorldDomination.HttpClient.Helpers/
